version: '3'
services:
  nginx:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.nginx
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/azureuser/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app1
      - app2
    networks:
      - icco-be
    restart: always

  app1:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.app
    container_name: icco-app1
    ports:
      - "5001:4001"
    networks:
      - icco-be
    restart: always

  app2:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.app
    container_name: icco-app2
    ports:
      - "5002:4001"
    networks:
      - icco-be
    restart: always

networks:
  icco-be:
